import NavBar from "@/components/Dashboard/NavBar";
import NotificationSide from "@/components/Dashboard/NotificationSide";
import SideBar from "@/components/Dashboard/SideBar";

export const metadata = {
  title: "PnG | Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative no-scrollbar">
        <div className=" flex fixed w-full">
          <SideBar />
          <div className="w-full flex flex-col">
            <NavBar />
            {children}
          </div>
          <NotificationSide />
        </div>
      </body>
    </html>
  );
}
