import { fetchData } from "@/Utils/API Call/fetchData";
import NavBar from "@/components/Dashboard/Layout/NavBar";
import NotificationSide from "@/components/Dashboard/Layout/NotificationSide";
import SideBar from "@/components/Dashboard/Layout/SideBar";
import { currentUser } from "@clerk/nextjs";

export const metadata = {
  title: "PnG | Dashboard",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children}) {

  const {username} = await currentUser();
  let company;
  let society;
  if(username){
     company = (await fetchData("get",`user/${username}/companies?select=companyID`)).companies ? ((await fetchData("get",`user/${username}/companies`))?.companies[0]) : null
     society = (await fetchData("get",`user/${username}/societies?select=societyID`)).societies ? ((await fetchData("get",`user/${username}/societies`))?.societies[0]) : null
  }
  
  const view = (company ? "company" : (society ? "society" : null))
  




  return (
    <html lang="en" className="dark:bg-slate-950 antialiased">
      <body className="relative no-scrollbar">
        <div className=" flex fixed w-full ">
          <SideBar view={view}/>
          <div className="flex flex-col w-full">
            <div className="pb-1">

            <NavBar />
            </div>
            <div className="">

           {children}
            </div>
          </div>
          <NotificationSide />
        </div>
      </body>
    </html>
  );
}
